### PR TITLE
Update jsonwebtoken to latest version

### LINKED ISSUE #25: Skip unknown JWKS Variants in JWK Store refresh
jwt-authorizer fails with a `AuthErrors::JwksRefreshError: error decoding response body: unknown variant 'RSA-OAEP'` when the JWKS URL contains a key where `alg` is `RSA-OAEP`.

It seems that https://github.com/cduvray/jwt-authorizer/blob/main/jwt-authorizer/src/jwks/key_store_manager.rs#L182 attempts to ignore a JWK if it's not decodable, but if a serialized JWK is unable to be cast into a JWK in https://github.com/cduvray/jwt-authorizer/blob/main/jwt-authorizer/src/jwks/key_store_manager.rs#L172 (which is the case if it's algorithm is not in https://github.com/Keats/jsonwebtoken/blob/master/src/algorithms.rs#L16), the entire method returns the AuthError.

### PR DESCRIPTION
**Pull request by blablacio**
Updates jsonwebtoken to latest version and also updates key algorithm handling when initializing key data.

Should close #25.

### CODE REVIEW

**Comment by cduvray** [comment]
Hi, thanks for this PR!
I think I will try to "regenerate" the test tokens without audiences (and with audiences for some tests), because it breaks too many tests. I will push it on the main branch you can then rebase on it.

**Comment by blablacio** [comment]
Hey, just noticed I missed one test in tonic. I think it's okay to not regenerate test tokens. The changes are required only because aud is validated against if it's present in the token in newer versions of jsonwebtoken.

**Comment by cduvray** [comment]
already added the tokens ;), this is also to test more more precisely with and without auditions.

**Comment by blablacio** [comment]
Seems tests are still passing without any changes on my side :)

**Pull request merged**
