### PR TITLE
feat: working but naive implementation of named cookie as jwt source

### PR DESCRIPTION
**Pull request by like-a-bause**
Hi there,
I have a use case with [hanko](https://github.com/teamhanko/hanko) where I want to define a cookie as the source for a JWT.
This is a working draft to support this use case.

Do you have any suggestions how this could be improved? I am aware that this might not be the most idiomatic solution.

### CODE REVIEW

**Comment by cduvray** [comment]
Thanks for your pr,

I would like to keep the default configuration as simple as possible with the most common and recommended defaults.
But we could integrate a jwt source as an optional configuration (propagating it to the authorizer).
The authorization header should be the default.

something like this: 

`JwtAuthorizer::from_oidc(...).jwt_source(JwtSource::Cookie("jwt-token")...`

Btw form encoded body parameters (described in  oauth 2.1, chapter 7.2.1.2), could also be supported later. 

(First I thaught an extractor function or trait could be better but it seems too complicated in Rust when propagating it from the conf with generics etc.)

**Comment by like-a-bause** [comment]
I see.
My thinking was: the extraction itself has nothing to do with the JwtAuthorizer itself. It doesn't care where the token comes from. Hence I put the configuration into the layer method. But I see your point and will try to alter the PR in this way.

When taking a look at the echo jwt middleware there could even be more sources:
https://github.com/labstack/echo/blob/f22ba6725c66896efdef029aaeb3bfc471f171c3/middleware/jwt.go#L83
So for example a different Header or even url param.

**Comment by like-a-bause** [comment]
I made the necessary changes. Could you please re-review?

**Comment by cduvray** [comment]
Cool, just a little detail, for having a consistent naming. I would prefer to name it just `jwt_source` instead of `with_jwt_source`.

**Comment by IgnisDa** [comment]
@like-a-bause Do you have an example of how to instantiate this? I am using hanko too!

**Pull request merged**
