### PR TITLE
Allow Authorizer to be accessed by public API

### PR DESCRIPTION
**Pull request by aotimme**
## Description
This introduces a public `authorizer()` method on the `JwtAuthorizer` struct so users of the library can directly access the `Authorizer` struct.

## Rationale
I wanted to be able to use this library with axum as an extractor, because I wanted to be able to use it optionally (https://docs.rs/axum/latest/axum/extract/index.html#optional-extractors). In particular, I have a graphql endpoint where I want the axum handler to look like
```rust
async graphql_handler(
    auth_user: Option<AuthenticatedUser>,
    // ...
) -> ... {
    // Execute the graphql where some queries require auth and some do not...
}
```

I was able to create an extractor but I needed access to the `Authorizer` so I could use its `check_auth()` method. Both `Authorizer` and `check_auth()` are public, but constructing `Authorizer` wasn't public...

So you see what I was trying to do, here is my code for an extractor that leverages this new method:
```rust
#[derive(Clone)]
pub struct AppState {
    pub db: DatabaseConnection,
    pub jwt_auth: Arc<Authorizer<ClaimsUser>>,
}

#[async_trait]
impl<S> FromRequestParts<S> for AuthenticatedUser
where
    AppState: FromRef<S>,
    S: Send + Sync,
{
    type Rejection = Response;

    async fn from_request_parts(parts: &mut Parts, state: &S) -> Result<Self, Self::Rejection> {
        let TypedHeader(Authorization(token)) =
            TypedHeader::<Authorization<Bearer>>::from_request_parts(parts, state)
                .await
                .map_err(|err| err.into_response())?;
        let app_state = AppState::from_ref(state);
        let claims_user = app_state.jwt_auth.check_auth(token.token()).await?.claims;

        let auth_user = get_authenticated_user(&app_state.db, claims_user)
            .await
            .map_err(|err| err.into_response())?;

        Ok(auth_user)
    }
}
```

As a side note, it would be nice to provide an extractor from this library, but I think to do that you need the user to both add something to the state in order to be able to use the extractor. Not quite as plug-and-play.

### CODE REVIEW

**Comment by aotimme** [comment]
What I'm trying to do might be a duplicate of what's provided in #16.

**Comment by vodik** [comment]
As I understand it, there's another reason to consider this change. GraphQL subscriptions are authenticated against a token passed as the first message inside the websocket.
```rust
async fn graphql_ws_handler(
    State(schema): State<SidneySchema>,
    protocol: GraphQLProtocol,
    websocket: WebSocketUpgrade,
) -> Response {
    async fn on_connection_init(value: serde_json::Value) -> Result<Data> {
        #[derive(Deserialize)]
        struct Payload {
            token: String,
        }

        if let Ok(payload) = serde_json::from_value::<Payload>(value) {
            let data = Data::default();
            // I need to validate the token here, I think
            data.insert(...);
            Ok(data)
        } else {
            Err("Token is required".into())
        }
    }

    websocket
        .protocols(ALL_WEBSOCKET_PROTOCOLS)
        .on_upgrade(move |stream| {
            GraphQLWebSocket::new(stream, schema, protocol)
                .on_connection_init(on_connection_init)
                .serve()
        })
}
```

There's currently no way, as far as I can see, to authenticate the token because I can't get access to the authorizer.

**Comment by vodik** [comment]
I got this working off the main branch by adding an implementation of `IntoLayer`:
```rust
impl<C> IntoLayer<C> for Arc<Authorizer<C>>
where
    C: Clone + DeserializeOwned + Send,
{
    fn into_layer(self) -> AsyncAuthorizationLayer<C> {
        AsyncAuthorizationLayer::new(vec![self])
    }
}
```
This lets me both have the authorizer for graphql subscription authentication while also being able to use the layer for authorizing other http endpoints.

I'll put it up as a PR once I get a chance to test it.

**Comment by humb1t** [comment]
@cduvray  what do you think about this PR or PR #16 ?

**Pull request closed without merging**
